version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:1.20
    restart: always
    volumes:
      - ./docker/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./code:/var/www/
    networks:
      - network
    ports:
      - 80:80
    depends_on:
      - app
  app:
    container_name: app
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    restart: always
    networks: 
      - network
    volumes: 
      - ./code:/var/www/
  mysql:
    container_name: mysql
    restart: always
    image: mysql:8.0
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes: 
      - ./docker/data/mysql:/var/lib/mysql
    ports:
      - 6033:3306
    networks: 
      - network
    
networks:
  network: