version: '3.8'

services:
  nginx:
    image: nginx:1.19
    restart: always
    volumes:
      - ./docker/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./code:/var/www/
    networks:
      - net
    ports:
      - "8080:80"
    depends_on:
      - app
  app:
    build: 
      context: ./
      dockerfile: ./docker/builds/php-fpm.Dockerfile
    restart: always
    networks: 
      - net
    volumes: 
      - ./code:/var/www/
    depends_on: 
      - mysql
  mysql:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - "3306:3306"
    volumes: 
      - db_data:/var/lib/mysql
    networks: 
      - net
    
networks:
  net:

volumes:
  db_data: